[package]
name = "nft-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.nft]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
